#!/usr/bin/env python
import json
from subprocess import Popen, DEVNULL
from xdg.BaseDirectory import xdg_config_home
from rofi import Rofi

filename = f"{xdg_config_home}/BraveSoftware/Brave-Browser/Default/Bookmarks"


def generate(rofi):
    def walk(node):
        for item in node:
            if "children" in item:
                yield from walk(item.get("children"))
            else:
                yield dict(name=item.get("name"), url=item.get("url"))

    with open(filename) as file:
        data = json.load(file)

    root = data.get("roots", {}).get("bookmark_bar", {}).get("children", [])
    for bookmark in sorted(walk(root), key=lambda b: b.get("name")):
        rofi.row(bookmark.get("name"), info=bookmark.get("url"))


def process(rofi):
    url = rofi.info(0)
    Popen(f"xdg-open {url}", shell=True, stdout=DEVNULL)


if __name__ == "__main__":
    r = Rofi()
    r.custom_entry(False)
    r.handle_startup(generate, process)
