#!/usr/bin/env python
from os import getenv, path
from pathlib import Path
from subprocess import Popen, DEVNULL
from rofi import Rofi

home = getenv("HOME")
terminal = getenv("TERMINAL")
editor = getenv("EDITOR")

basedir = f"{home}/.dotfiles"
ignored_extensions = [
    ".pyc",
    ".png",
]


def generate(rofi):
    files = []
    for entry in Path(basedir).glob("[!.git]*"):
        if not entry.is_dir():
            continue

        files.extend([
            file
            for file
            in Path(entry).rglob("*")
            if not file.is_dir() and file.suffix not in ignored_extensions
        ])

    for file in sorted(files):
        rofi.row(file.relative_to(basedir), info=file)


def process(rofi):
    file = rofi.info(0)
    Popen(f"{terminal} {editor} {file}", cwd=path.dirname(file), shell=True,
          stdout=DEVNULL)


if __name__ == "__main__":
    r = Rofi()
    r.custom_entry(False)
    r.handle_startup(generate, process)
