#!/usr/bin/env python
from subprocess import Popen, DEVNULL
from os import getenv, path
from pathlib import Path
from functools import partial
from rofi import Rofi

terminal = getenv("TERMINAL", "")
editor = getenv("EDITOR", "")
home = str(Path.home())
basedir = f"{home}/dev"


def generate(rofi, args):
    def walk(root):
        for entry in Path(root).iterdir():
            if entry.is_file():
                continue

            if path.isdir(path.join(entry, ".git")):
                yield entry
            else:
                yield from walk(entry)

    for project in sorted(walk(basedir), key=path.basename):
        name = path.basename(project)
        location = path.dirname(project).replace(home, '~')
        rofi.row(f"<b>{name: <20}</b>&#10;<small>{location}</small>", icon='folder-development',
                info=project, meta=project)


def process(rofi, selected, args):
    project = rofi.info(0)
    popen = partial(Popen, cwd=project, shell=True, stdout=DEVNULL)
    popen(terminal)


if __name__ == "__main__":
    r = Rofi()
    r.custom_entry(False)
    r.markup_rows(True)
    r.handle_startup(generate, process)
