#!/bin/env python

import sys
from libqtile.command.client import InteractiveCommandClient
from rofi import Rofi

client = InteractiveCommandClient()


def generate(rofi):
    windows = [
        w | client.window[w["id"]].inspect()
        for w in client.windows()
        if w["group"] is not None
    ]

    import time
    for win in windows:
        rofi.row(f"{win['group']: <10} {win['wm_class'][0]: <20} {win['name']}", info=win["id"])


def process(rofi):
    win_id = int(rofi.info(0))
    win = client.window[win_id]
    group = win.group

    if group.info()['name'] == "scratchpad":
        dropdowns = [group.dropdown_info(d) for d in group.dropdown_info()["dropdowns"]]
        dropdown = next((d for d in dropdowns if d.get("window", {}).get("id", None) == win_id), None)
        group.dropdown_toggle(dropdown["name"])
    else:
        group.toscreen(toggle=False)
        group.focus_by_name(win.info()["name"])


if __name__ == "__main__":
    rofi = Rofi()
    rofi.custom_entry(False)

    if len(sys.argv) == 1:
        generate(rofi)
    else:
        process(rofi)
