#!/usr/bin/env python
from subprocess import Popen, DEVNULL
from rofi import Rofi

actions = [
    dict(name="Suspend", cmd="systemctl suspend", confirm=False),
    dict(name="Logout", cmd="qtile cmd-obj -o cmd -f shutdown"),
    dict(name="Reboot", cmd="systemctl reboot"),
    dict(name="Shutdown", cmd="systemctl poweroff"),
    dict(name="Restart WM", cmd="qtile cmd-obj -o cmd -f restart", confirm=False)
]


def generate(rofi):
    for idx, action in enumerate(actions):
        rofi.row(action["name"], info=idx)


def process(rofi):
    action = actions[int(rofi.info(0))]
    if action.get("confirm", True):
        if rofi.info(1) is None:
            rofi.prompt(f"confirm {action.get('name')}?")
            rofi.row("yes", info="y")
            rofi.row("no", info="n")
            return

        if rofi.info(1) == "n":
            return

    action = actions[int(rofi.info(0))]
    Popen(action.get("cmd"), shell=True, stdout=DEVNULL)


if __name__ == "__main__":
    r = Rofi()
    r.custom_entry(False)
    r.handle_startup(generate, process)
