#!/usr/bin/env python
from subprocess import Popen, DEVNULL
from rofi import Rofi

actions = [
    dict(name="Suspend", icon="system-suspend", cmd="systemctl suspend", confirm=False),
    dict(name="Lock", icon="system-lock-screen", cmd="i3lock --blur 10", confirm=False),
    dict(name="Logout", icon="system-log-out", cmd="qtile cmd-obj -o cmd -f shutdown"),
    dict(name="Reboot", icon="system-reboot", cmd="systemctl reboot"),
    dict(name="Shutdown", icon="system-shutdown", cmd="systemctl poweroff"),
    dict(name="Update", icon="system-software-update", cmd="kitty topgrade", confirm=False),
]


def generate(rofi, args):
    for idx, action in enumerate(actions):
        rofi.row(f'<b>{action["name"]}</b>&#10;<small>{action["cmd"]}</small>', icon=action["icon"], info=idx)


def process(rofi, selected, args):
    action = actions[int(rofi.info(0))]
    if action.get("confirm", True):
        if rofi.info(1) is None:
            rofi.prompt("confirm?")
            rofi.row(f"<b>{action['name']}</b>&#10;<small>{action['cmd']}</small>", icon=action['icon'], info="y")
            return

        if rofi.info(1) == "n":
            return

    action = actions[int(rofi.info(0))]
    Popen(action.get("cmd"), shell=True, stdout=DEVNULL)


if __name__ == "__main__":
    r = Rofi()
    r.custom_entry(False)
    r.markup_rows(True)
    r.handle_startup(generate, process)
