local g = vim.g
g.mapleader = ' ' -- space as the leader key

local o = vim.opt
o.backup = false
o.colorcolumn = '120'
o.completeopt = { 'menu', 'menuone', 'noinsert' }
o.confirm = true
o.cursorline = true
o.expandtab = false
o.foldlevel = 99
o.foldlevelstart = -1
o.foldenable = true
o.hidden = true
o.hlsearch = false
o.ignorecase = true
o.linebreak = true
o.list = true
o.listchars = { trail = '·', tab = '  ' }
o.mouse = 'a'
o.numberwidth = 2
o.relativenumber = true
o.ruler = false
o.scrolloff = 3
o.shiftwidth = 2
o.shortmess:append({ I = true, S = true, a = true, s = true, c = true })
o.showcmd = false
o.showmode = false
o.sidescroll = 1
o.sidescrolloff = 5
o.signcolumn = 'yes:1'
o.smartcase = true
o.smartindent = false
o.spelllang = { 'en_us', 'pt_br' }
o.spelloptions = 'camel'
o.softtabstop = 2
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.tabstop = 2
o.termguicolors = true
o.title = true
o.ttimeoutlen = 0
o.undofile = true
o.updatetime = 250
o.virtualedit = ''
o.wildmode = 'full'
o.wrap = false
