return {
	lsp_icons = {
		Array = "  ",
		Boolean = "  ",
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Copilot = " ",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = " ",
		Interface = " ",
		Keyword = " ",
		Method = " ",
		Module = "󰅩 ",
		Namespace = "󰅩 ",
		Null = "  ",
		Number = "  ",
		Object = "  ",
		Operator = " ",
		Package = "  ",
		Property = " ",
		Reference = " ",
		Snippet = " ",
		String = "  ",
		Struct = " ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Value = " ",
		Variable = " ",
	},
}
