set nocompatible
set encoding=utf-8
set termguicolors
set guicursor=
set wildmenu wildmode=full
set number relativenumber
set colorcolumn=120
set hidden
set shortmess-=S
set scrolloff=10
set sidescroll=1
set sidescrolloff=10
set title
set splitbelow
set splitright
set tabstop=2
set softtabstop=2
set shiftwidth=2
set noexpandtab
set ttimeoutlen=0
set virtualedit=all
set laststatus=2
set smartindent
set smarttab
set incsearch
set nohlsearch
set noshowmode
set nowrap
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set ignorecase
set smartcase
set cursorline

call plug#begin('~/.vim/plugged')
Plug 'joshdick/onedark.vim'
Plug 'sheerun/vim-polyglot'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'preservim/nerdcommenter'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-eunuch'
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'ntpeters/vim-better-whitespace'
Plug 'terryma/vim-expand-region'
Plug 'mg979/vim-visual-multi'
Plug 'easymotion/vim-easymotion'
Plug 'machakann/vim-highlightedyank'
Plug 'chaoren/vim-wordmotion'
"Plug 'fatih/vim-go'
call plug#end()

syntax on
colorscheme onedark

let &t_SI = "\e[5 q"
let &t_rR = "\e[4 r"
let &t_EI = "\e[1 q"

let g:airline_theme='violet'
let g:airline_powerline_fonts=1
let g:airline_skip_empty_sections=1
let g:airline_section_z=airline#section#create(['%3p%% ', '%3l:%-3v'])
let g:airline#extensions#tabline#enabled=1

let NERDTreeDirArrows=1
let NERDTreeShowHidden=1

let g:highlightedyank_highlight_duration = 300

let g:fzf_layout = { 'down': '40%' }
let g:fzf_files_options = '--no-exact --tiebreak=end --prompt="> "'

let mapleader="\<Space>"
nnoremap <silent> <leader>tt :NERDTreeToggle %<CR>
nnoremap <silent> <leader>tf :NERDTreeFind %<CR>
nnoremap <silent> <leader>w :w<CR>
nnoremap <silent> <leader>x :bd<CR>
nnoremap <silent> <leader>q :x<CR>
nnoremap <silent> <leader>j :Files<CR>
nnoremap <silent> <leader>f :Rg<CR>
nnoremap <silent> <leader>b :Buffers<CR>
nnoremap <silent> <leader>d Yp
nnoremap <silent> <leader>i i<SPACE><ESC>r

nnoremap <silent> <C-k> :bnext<CR>
nnoremap <silent> <C-j> :bprevious<CR>
nnoremap <silent> <leader>o mao<ESC>`a
nnoremap <silent> <leader>O maO<ESC>`a
nnoremap <silent> <C-down> :m+1<CR>
nnoremap <silent> <C-up> :m-2<CR>
nnoremap <silent> U <C-R>
"map s <Plug>(easymotion-sl)

augroup CUSTOM
	autocmd!
	autocmd FocusLost * silent! wa
	autocmd FileType markdown setlocal spell spelllang=en_us,pt_br
	autocmd FileType gitcommit setlocal spell spelllang=en_us,pt_br
	autocmd FileType markdown setlocal complete+=kspell
	autocmd FileType gitcommit setlocal complete+=kspell
augroup END

