set nocompatible
set encoding=utf-8
set termguicolors
set guicursor=
set wildmenu wildmode=full
set number relativenumber
set colorcolumn=120
set hidden
set shortmess-=S
set scrolloff=10
set sidescroll=1
set sidescrolloff=10
set title
set splitbelow
set splitright
set tabstop=2
set softtabstop=2
set shiftwidth=2
set noexpandtab
set ttimeoutlen=0
set virtualedit=all
set laststatus=2
set smartindent
set smarttab
set incsearch
set nohlsearch
set noshowmode
set nowrap
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile

call plug#begin('~/.vim/plugged')
Plug 'joshdick/onedark.vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'preservim/nerdcommenter'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'ntpeters/vim-better-whitespace'
Plug 'terryma/vim-expand-region'
Plug 'mg979/vim-visual-multi'
Plug 'vimwiki/vimwiki'
Plug 'fatih/vim-go'
Plug 'easymotion/vim-easymotion'
Plug 'machakann/vim-highlightedyank'
Plug 'tpope/vim-surround'
call plug#end()

syntax on
colorscheme onedark

let g:airline_theme='violet'
let g:airline_powerline_fonts=1
let g:airline_skip_empty_sections=1
let g:airline_section_z=airline#section#create(['%3p%% ', '%3l:%-3v'])
let g:airline#extensions#tabline#enabled=1

let NERDTreeDirArrows=1
let NERDTreeShowHidden=1

let g:highlightedyank_highlight_duration = 300

let mapleader="\<Space>"
nnoremap <C-t> :NERDTreeToggle %<CR>
nnoremap <silent> <Leader>x :bd<CR>
nnoremap <silent> <Leader>q :x<CR>
nnoremap <silent> <Leader>p :Files<CR>
nnoremap <silent> <Leader>d Yp
nnoremap <silent> <C-j> :bprevious<CR>
nnoremap <silent> <C-k> :bnext<CR>
nnoremap <silent> <Leader>o mao<ESC>`a
nnoremap <silent> <Leader>O maO<ESC>`a
nnoremap <silent> <C-down> :m+1<CR>
nnoremap <silent> <C-up> :m-2<CR>
"map s <Plug>(easymotion-sl)

augroup CUSTOM
	autocmd!
	autocmd FileType markdown setlocal spell
	autocmd FileType gitcommit setlocal spell
	autocmd FileType markdown setlocal complete+=kspell
	autocmd FileType gitcommit setlocal complete+=kspell
augroup END

