git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  log:
    order: date-order
os:
  editPreset: nvim
gui:
  nerdFontsVersion: "3"
  showFileTree: false
  showBottomLine: false
  expandFocusedSidePanel: true
  timeFormat: "02/03/06"
  shortTimeFormat: "15:04"
  authorColors:
    'Michael Benford': '#f5a97f'
    '*': '#c6a0f6'
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#2e3c64"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
