git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  log:
    order: date-order
os:
  editPreset: nvim
gui:
  nerdFontsVersion: "3"
  showFileTree: false
  showBottomLine: false
  expandFocusedSidePanel: true
  timeFormat: "02/03/06"
  shortTimeFormat: "15:04"
  authorColors:
    'Michael Benford': '#f5a97f'
    '*': '#c6a0f6'
  theme:
    activeBorderColor:
      - '#8aadf4'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    selectedRangeBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8aadf4'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'
