set colorcolumn=120
set cursorline
set hidden
set ignorecase
set nobackup
set noexpandtab
set nohlsearch
set noshowcmd
set noshowmode
set noswapfile
set nowrap
set number relativenumber
set scrolloff=5
set shiftwidth=2
set shortmess-=S
set sidescroll=1
set sidescrolloff=10
set smartcase
set smartindent
set softtabstop=2
set splitbelow
set splitright
set tabstop=2
set termguicolors
set title
set ttimeoutlen=0
set undofile
set virtualedit=all
set wildmode=full
