# cdpath
cdpath=(. $HOME)

# oh my zsh
ZSH_THEME_TERM_TITLE_IDLE="%~"

# zsh-autosuggest plugin
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=245'
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_HISTORY_IGNORE="?(#c100,)"

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden"
export FZF_DEFAULT_OPTS_FILE="$XDG_CONFIG_HOME/fzf/config"

# golang
export GOPATH=$HOME/.go
path+=$GOPATH/bin

# poetry
path+=$HOME/.poetry/bin

# cargo
path+=$HOME/.cargo/bin

# gcloud
source $HOME/downloads/google-cloud-sdk/path.zsh.inc

# work
[[ -f "$ZDOTDIR/.zshenv_work" ]] && source "$ZDOTDIR/.zshenv_work"
