# path
path+=$HOME/.local/bin
path+=$HOME/.dotfiles/bin
typeset -U path

# cdpath
cdpath=(. $HOME)

# zsh-autosuggest plugin
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=245'
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_HISTORY_IGNORE="?(#c100,)"

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden"
export FZF_DEFAULT_OPTS='--no-info --height=30%'

# golang
export GOPATH=$HOME/.go
path+=$GOPATH/bin

# rust
source "$HOME/.cargo/env"
