# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

# basic configuration
ZSH_THEME="powerlevel10k/powerlevel10k"
CASE_SENSITIVE=false
HYPHEN_INSENSITIVE=true
DISABLE_AUTO_UPDATE=false
DISABLE_UPDATE_PROMPT=false
DISABLE_MAGIC_FUNCTIONS=true
ENABLE_CORRECTION=false
COMPLETION_WAITING_DOTS=false
DISABLE_UNTRACKED_FILES_DIRTY=true

# history configuration
HISTFILE="$XDG_CONFIG_HOME/zsh/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
HISTORY_IGNORE="(ls|ll|cd|\.\.|\.\.\.|\.\.\.\.|gc|gst|gau|ga|gco|gup)"
HIST_STAMPS="yyyy-mm-dd"

# plugins
plugins=(
	z
	vi-mode
	asdf
	bgnotify
	colored-man-pages
	common-aliases
	fast-syntax-highlighting
	fzf
	git
	sudo
	archlinux
	zsh-autosuggestions
)

# Oh My ZSH
source $ZSH/oh-my-zsh.sh

# custom zsh options
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt hist_save_no_dups
unsetopt share_history

# custom aliases
source $ZDOTDIR/.zsh_aliases

# custom key bindings
source $ZDOTDIR/.zsh_bindings

# custom functions
fpath=($ZDOTDIR/.zfunc "${fpath[@]}")
autoload -U $fpath[1]/*(.:t)

# powerlevel10k
[[ ! -f $XDG_CONFIG_HOME/p10k/config.zsh ]] || source $XDG_CONFIG_HOME/p10k/config.zsh
