# basic configuration
CASE_SENSITIVE=false
HYPHEN_INSENSITIVE=true
DISABLE_AUTO_UPDATE=true
DISABLE_UPDATE_PROMPT=false
DISABLE_MAGIC_FUNCTIONS=true
ENABLE_CORRECTION=false
COMPLETION_WAITING_DOTS=false
DISABLE_UNTRACKED_FILES_DIRTY=true
DISABLE_AUTO_TITLE=true

# history configuration
HISTFILE="$ZDOTDIR/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
HISTORY_IGNORE="$(cat $ZDOTDIR/history_ignore | tr '\n' '|')"
HIST_STAMPS="yyyy-mm-dd"

# plugins
plugins=(
	vi-mode
	archlinux
	bgnotify
	colored-man-pages
	common-aliases
	copybuffer
	encode64
	eza
	fancy-ctrl-z
	fast-syntax-highlighting
	fzf
	fzf-tab
	gcloud
	git
	httpie
	sudo
	systemd
	terraform
	zsh-autosuggestions
)

# Oh My ZSH
source $HOME/.oh-my-zsh/oh-my-zsh.sh
ZSH_THEME_TERM_TITLE_IDLE=""

# custom zsh options
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt hist_save_no_dups
unsetopt share_history

# styles
source $ZDOTDIR/.zsh_styles

# custom aliases
source $ZDOTDIR/.zsh_aliases

# custom key bindings
source $ZDOTDIR/.zsh_bindings

# custom functions
fpath=($ZDOTDIR/.zfunc "${fpath[@]}")
autoload -U $fpath[1]/*(.:t)

# zoxide
eval "$(zoxide init zsh)"

# Oh My Posh
eval "$(oh-my-posh init zsh --config $XDG_CONFIG_HOME/oh-my-posh/config.yaml)"
