export ZSH="$HOME/.oh-my-zsh"

# basic configuration
CASE_SENSITIVE=false
HYPHEN_INSENSITIVE=true
DISABLE_AUTO_UPDATE=true
DISABLE_UPDATE_PROMPT=false
DISABLE_MAGIC_FUNCTIONS=true
ENABLE_CORRECTION=false
COMPLETION_WAITING_DOTS=false
DISABLE_UNTRACKED_FILES_DIRTY=true

# history configuration
HISTFILE="$XDG_CONFIG_HOME/zsh/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
HISTORY_IGNORE="$(cat $XDG_CONFIG_HOME/zsh/history_ignore | tr '\n' '|')"
HIST_STAMPS="yyyy-mm-dd"

# plugins
plugins=(
	asdf
	bgnotify
	colored-man-pages
	common-aliases
	fast-syntax-highlighting
	fzf
	git
	sudo
	archlinux
	zsh-autosuggestions
	httpie
	systemd
	encode64
	fzf-tab
	terraform
	gcloud
	copybuffer
	eza
	fancy-ctrl-z
)

# Oh My ZSH
source $ZSH/oh-my-zsh.sh
ZSH_THEME_TERM_TITLE_IDLE="%1d - $(basename $SHELL)"

# custom zsh options
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt hist_save_no_dups
unsetopt share_history

# styles
source $ZDOTDIR/.zsh_styles

# custom aliases
source $ZDOTDIR/.zsh_aliases

# custom key bindings
source $ZDOTDIR/.zsh_bindings

# custom functions
fpath=($ZDOTDIR/.zfunc "${fpath[@]}")
autoload -U $fpath[1]/*(.:t)

# zoxide
eval "$(zoxide init zsh)"
#
# Oh My Posh
eval "$(oh-my-posh init zsh --config $XDG_CONFIG_HOME/oh-my-posh/config.yaml)"
